# Generated by Django 3.2 on 2023-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttheanimal',
            name='type_of_animal',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('RABBIT', 'Rabbit'), ('GUINEA PIGS', 'Guinea pigs'), ('BIRDS', ' Birds')], default=1, max_length=11),
        ),
    ]
