# Generated by Django 3.2 on 2023-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='name',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='statement',
            field=models.TextField(default='Your statement', max_length=500),
        ),
    ]
