# Generated by Django 3.2 on 2023-02-16 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_pet_parent', models.CharField(blank=True, max_length=40, null=True)),
                ('User_email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('other_pets', models.CharField(blank=True, choices=[('NO', 'No'), ('YES', 'Yes')], default=1, max_length=3)),
                ('please_give_details', models.TextField(max_length=400)),
                ('what_type_of_pet', models.CharField(blank=True, choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('RABBIT', 'Rabbit'), ('GUINEA PIGS', 'Guinea pigs'), ('BIRDS', ' BIRDS')], default=1, max_length=11)),
                ('description_of_pet_you_want', models.TextField(max_length=400)),
                ('where_will_the_pet_be_kept', models.CharField(blank=True, choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside'), ('ANIMAL HOUSE', 'Outdoor animal house')], default=1, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
