# Generated by Django 3.2 on 2023-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionquestion',
            name='perspective_pet_parent',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='adoptionquestion',
            name='please_give_details',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
